#-------------------------------------------------------------------------------
# Copyright (C) 2021-2022 AIR Institute
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
#-------------------------------------------------------------------------------
version: '3'

services:
  smartclide_dle:
    restart: unless-stopped
    build: .
    working_dir: /app/smartclide-smart-assistant/smartclide-dle/smartclide-dle
    command: smartclide-dle
    ports:
      - "5001:5001"
  smartclide_smart_assistant:
    restart: unless-stopped
    build: .
    working_dir: /app/smartclide-smart-assistant/smartclide-dle/smartclide-smart-assistant
    command: smartclide-smart-assistant
    ports:
      - "5000:5000"
