name: deploy

on:
  push:
    branches: main

jobs:
  download: 
    runs-on: [self-hosted, Linux, X64]  
    steps:  
    - name: download new changes
      uses: actions/checkout@v2
  build:
    runs-on: [self-hosted, Linux, X64]  
    needs: download
    steps:  
    - name: install package
      run: sudo python3 -m pip install . --upgrade
    - name: restart smartclide-dle
      run: sudo pm2 restart smartclide-smart-assistant smartclide-dle
